### ISSUE TITLE
[webpack-scripts] are broken in folders with spaces due to postcss-normalize

### ISSUE THREAD

**Issue by ThaNarie** [mediamonks/pota#82]
```
> pota dev

Error loading dependency '@pota/react-webpack-scripts/config':
Error: Cannot find module '@csstools/normalize.css'
Require stack:
- /Users/xxx/Desktop/MediaMonks%20Working%20Directory/xxx/node_modules/postcss-normalize/index.mjs
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at resolve (file:///Users/xxx/Desktop/MediaMonks%20Working%20Directory/xxx/node_modules/postcss-normalize/index.mjs:57:46)
    at file:///Users/xxx/Desktop/MediaMonks%20Working%20Directory/xxx/node_modules/postcss-normalize/index.mjs:15:22
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadDependencies (file:///Users/xxx/Desktop/MediaMonks%20Working%20Directory/xxx/node_modules/@pota/cli/lib/createCommand.js:48:51)
    at async file:///Users/xxx/Desktop/MediaMonks%20Working%20Directory/xxx/node_modules/@pota/cli/lib/createCommand.js:68:30 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xxx/Desktop/MediaMonks%20Working%20Directory/xxx/node_modules/postcss-normalize/index.mjs'
  ]
}
```

This is because `postcss-normalize` has a funky way of resolving modules.

**For now, a solution would be to create a big warning (or even abort with an error), if users are running `pota-cli` in a project folder that has spaces somewhere in the path.**

**Comment by ThaNarie** [comment]
postcss-normalize has fixed this in version 12, so we can update the dependency.
